# Generated by Django 5.1.4 on 2025-11-24 00:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0005_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('deliver_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('kwargs', models.JSONField(default=dict)),
                ('timeout', models.IntegerField(default=60)),
                ('on_success', models.JSONField(null=True)),
                ('on_failure', models.JSONField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error', models.TextField(null=True)),
                ('claimed_proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_events', to='machine.process')),
                ('emitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emitted_events', to='machine.process')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='workers.event')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
