# Generated by Django 5.1.4 on 2025-11-24 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_snapshot_downloaded_at'),
        ('machine', '0005_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveresult',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='iface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.networkinterface', verbose_name='Network Interface Used'),
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Any extra notes this ArchiveResult should have'),
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='num_uses_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='num_uses_succeeded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='output_dir',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='retry_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
